//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataVisualization.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string Identifier { get; set; }
        public string SKU { get; set; }
        public string Description { get; set; }
        public string ControlNumber { get; set; }
        public string LotNumber { get; set; }
        public string Revision { get; set; }
        public string Series { get; set; }
        public string ItemCode { get; set; }
        public string ItemType { get; set; }
        public string Subinventory { get; set; }
        public Nullable<double> NetWeight { get; set; }
        public Nullable<double> GrossWeight { get; set; }
        public string WeightUom { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<double> Volume { get; set; }
        public string DimensionUom { get; set; }
        public string Size { get; set; }
        public string Bags { get; set; }
        public Nullable<int> Pieces { get; set; }
        public Nullable<System.DateTime> PackDate { get; set; }
        public string Packaging { get; set; }
        public string PackagingCode { get; set; }
        public string SONumber { get; set; }
        public string SoldToCustomer { get; set; }
        public string CustomerStatus { get; set; }
        public string PONumber { get; set; }
        public string VendorName { get; set; }
        public string ASNNumber { get; set; }
        public string NAEL { get; set; }
        public string Color { get; set; }
        public string Grade { get; set; }
        public string Comment { get; set; }
        public string Reference { get; set; }
        public Nullable<int> Stackability { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string WarehouseStatus { get; set; }
        public string QualityStatus { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> StorageLocationId { get; set; }
        public Nullable<int> StackId { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public byte[] rowversion { get; set; }
        public Nullable<bool> IsOnShipment { get; set; }
        public Nullable<int> Cartons { get; set; }
        public string Planner { get; set; }
        public Nullable<bool> Priority { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Owner { get; set; }
        public string Critical { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual Stack Stack { get; set; }
    }
}
