//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataVisualization.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stack
    {
        public Stack()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int Id { get; set; }
        public string Identifier { get; set; }
        public string SKU { get; set; }
        public string Revision { get; set; }
        public Nullable<int> Pieces { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string WarehouseStatus { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
