//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataVisualization.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public string Type { get; set; }
        public string Reference { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public string SKU { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<int> Pieces { get; set; }
        public string Locator { get; set; }
        public int CustomerId { get; set; }
        public string Employee { get; set; }
        public Nullable<bool> IsReadyToExport { get; set; }
        public Nullable<bool> IsCustomerNotified { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> Cartons { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
